---
- name: Deploy server using Cloudformation
  hosts:
    - eaasitest
  connection: local
  gather_facts: false
  become: false
  vars:
    machine_name: '{{ tagName }}'
    required:
      Name: '{{ tagName }}'
      Owner: '{{ tagOwner }}'
      Contact: '{{ tagContact }}'
      Description: '{{ tagDescription }}'
      Service: '{{ tagService }}'
      FQDN: '{{ host }}'
    machine_parameters:
      SecurityGroupIds: '{{ security_groups }}'
      KeyName: eaasi-test
      Environment: '{{ tagEnvironment }}'
      InstanceType: '{{ instance_type }}'
      AMI: '{{ ami_id }}'
      SubnetId: '{{ subnet_id }}'
      PrivateIP: '{{ ansible_ssh_host }}'
      ElasticIPAllocation: '{{ elastic_IP_alloc }}'
# Libnd Instance Profile
#      IamInstanceProfile: 'iam-BasicInstanceProfile-1WT0D3FLL2TQV'
# Testlibnd Instance Profile
      IamInstanceProfile: 'iam-BasicInstanceProfile-17NSUPONCJXZL'
  tasks:
    - name: Attach the Secondary Volume (if there is one)
      ec2_vol:
        instance: "{{ instance_id }}"
        id: "{{ SecondaryVolume }}"
        device_name: "{{ volume_device }}"
        region: us-east-1
        delete_on_termination: no
        state: present
      when: SecondaryVolume != ""

    - name: Tag the Secondary Volume (if there is one)
      ec2_tag:
        resource: "{{ SecondaryVolume }}"
        region: us-east-1
        tags:
          Backup: "{{ tagBackup }}"
          Name: "{{ tagName }}-vol2"
        state: present
      when: SecondaryVolume != ""
    
    - name: mount /eaas-home
      mount: 
        path: /eaas-home
        src: "{{ volume_device }}"
        fstype: ext4
        opts: rw
        state: mounted
      become: true

